# Generated by Django 3.1.2 on 2020-10-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='业务线')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机房')),
                ('floor', models.IntegerField(default=1, verbose_name='楼层')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='状态')),
                ('cabinet_num', models.CharField(blank=True, max_length=32, null=True, verbose_name='机柜号')),
                ('cabinet_order', models.CharField(blank=True, max_length=32, null=True, verbose_name='机柜中序号')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='最近汇报的时间')),
                ('os_platform', models.CharField(blank=True, max_length=16, null=True, verbose_name='系统')),
                ('os_version', models.CharField(blank=True, max_length=16, null=True, verbose_name='系统版本')),
                ('manufacturer', models.CharField(blank=True, max_length=32, null=True, verbose_name='制造商')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='型号')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='序列号')),
                ('cpu_count', models.IntegerField(blank=True, null=True, verbose_name='cpu个数')),
                ('cpu_physical_count', models.IntegerField(blank=True, null=True, verbose_name='cpu物理个数')),
                ('cpu_model', models.CharField(blank=True, max_length=64, null=True, verbose_name='cpu型号')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businessunit', verbose_name='业务线')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.idc', verbose_name='机房')),
            ],
        ),
        migrations.CreateModel(
            name='NetWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='网卡名称')),
                ('up', models.BooleanField(default=False)),
                ('hwaddr', models.CharField(blank=True, max_length=64, null=True, verbose_name='网卡mac地址')),
                ('ipaddrs', models.CharField(blank=True, max_length=256, null=True, verbose_name='ip地址')),
                ('netmask', models.CharField(blank=True, max_length=32, null=True, verbose_name='子网掩码')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.server', verbose_name='服务器')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='容量')),
                ('slot', models.CharField(max_length=32, verbose_name='槽位')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='型号')),
                ('speed', models.CharField(blank=True, max_length=16, null=True, verbose_name='速度')),
                ('manufacturer', models.CharField(blank=True, max_length=32, null=True, verbose_name='制造商')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='序列号')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.server', verbose_name='服务器')),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=32, verbose_name='槽位')),
                ('pd_type', models.CharField(max_length=32, verbose_name='类型')),
                ('capacity', models.CharField(max_length=32, verbose_name='容量')),
                ('model', models.CharField(max_length=64, verbose_name='型号')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.server', verbose_name='服务器')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.server', verbose_name='服务器')),
            ],
        ),
    ]
