# Generated by Django 3.1.2 on 2020-10-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='broadcast',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='广播'),
        ),
    ]
